language: rust
rust:
  - stable
  - beta
matrix:
  allow_failures:
    - rust: beta
before_script:
  - rustup component add clippy
  - |
    travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.8.tar.gz | tar xz
    cd SDL2-2.0.8
    ./configure
    make
    sudo make install
    cd ..
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo doc
  - cargo build --release
  - cargo test
  - cargo test --release
  - cargo bench
